# Generated by Django 3.2.7 on 2021-10-06 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('ip_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=255)),
                ('equipamento', models.CharField(max_length=255)),
                ('IP', models.CharField(max_length=255)),
                ('MAC', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogger',
        ),
    ]
