# Generated by Django 3.2.7 on 2021-10-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20211008_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='DNS',
            new_name='netmask',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='ip_key',
        ),
        migrations.AlterField(
            model_name='adress',
            name='DHCP',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='adress',
            name='IP',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
