# Generated by Django 3.2.7 on 2021-10-11 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20211010_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='ip_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adress',
            name='IP',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='adress',
            name='netmask',
            field=models.CharField(max_length=16),
        ),
    ]
