# Generated by Django 3.2.7 on 2021-10-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20211011_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='ip_key',
        ),
        migrations.AddField(
            model_name='adress',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
