# Generated by Django 3.2.7 on 2021-10-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_alter_adress_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='DHCP',
        ),
        migrations.AddField(
            model_name='adress',
            name='dhcp',
            field=models.CharField(choices=[('sim', 'sim'), ('nao', 'nao')], default='sim', max_length=3),
        ),
        migrations.AddField(
            model_name='adress',
            name='modelo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='MAC',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adress',
            name='equipamento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adress',
            name='identificador',
            field=models.CharField(max_length=200),
        ),
    ]
