# Generated by Django 3.2.7 on 2021-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20211027_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='dhcp',
        ),
        migrations.AddField(
            model_name='adress',
            name='DHCP',
            field=models.CharField(default='Nao', max_length=255),
        ),
    ]
